name: publish-to-spacedock

on:
  release:
    types: [released]

jobs:
  publish-to-spacedock:
    uses: KSPModdingLibs/KSPBuildTools/.github/workflows/publish-to-spacedock.yml@0.0.4
    with:
      spacedock-username: ${{ vars.SPACEDOCK_USERNAME }}
      mod-id: ${{ vars.SPACEDOCK_MOD_ID }}
    secrets:
      spacedock-password: ${{ secrets.SPACEDOCK_PASSWORD }}
